// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://inxxdwahgzleaplirhwh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlueHhkd2FoZ3psZWFwbGlyaHdoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMwNjE4ODgsImV4cCI6MjA1ODYzNzg4OH0.T6PzDwmg4Yrh9DKe_BNLQgkV3GIzJU_fJxuKnWzjwU8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);