// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vbshuwdbpkccpnkuxsca.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZic2h1d2RicGtjY3Bua3V4c2NhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI4NzkxMTUsImV4cCI6MjA1ODQ1NTExNX0.NZkpcm-hdbL9qswlNKZgbO3CAGBtWQexFSOwgJsySTY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);